export default {
  SAVE_NOTIFY_ID: 'SAVE_NOTIFY_ID',
  SAVE_USER_INFO: 'SAVE_USER_INFO',
  GET_PEOPLE_INFO: 'GET_PEOPLE_INFO',
  GET_USER_INTEGRAL: 'GET_USER_INTEGRAL',

  SAVE_TROUBLE_LEVEL: 'SAVE_TROUBLE_LEVEL',
  SAVE_TROUBLE_TYPE: 'SAVE_TROUBLE_TYPE',

  GET_MESSAGE_INFO: 'GET_MESSAGE_INFO',
  CLEAR: 'CLEAR', 
  SAVE_COURSE_INFO: 'SAVE_COURSE_INFO',


  SAVE_MEETING_TYPE: 'SAVE_MEETING_TYPE',
  SAVE_MEETING_ROOM: 'SAVE_MEETING_ROOM',
  SAVE_MEETING_ID: 'SAVE_MEETING_ID',
	SAVE_DEVICE_TYPE: 'SAVE_DEVICE_TYPE', 
};