# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyApp
    rn_path = '../node_modules/react-native'
    pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'Core',
        'CxxBridge',
        'DevSupport',
        'RCTText',
        'RCTNetwork',
        'RCTWebSocket',
        'RCTAnimation',
        'RCTActionSheet',
        'RCTGeolocation',
        'RCTImage',
        'RCTLinkingIOS',
        'RCTSettings',
        'RCTVibration',
        'ART',
        'RCTPushNotification',
        'RCTBlob',
      ]
      pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
      pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
      pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

      pod 'react-native-baidu-map', :podspec => '../node_modules/react-native-baidu-map/ios/react-native-baidu-map.podspec'
      pod 'react-native-camera', path: '../node_modules/react-native-camera'
      pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
      pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

      pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

      pod 'react-native-ksyvideo', :path => '../node_modules/react-native-ksyvideo'

      pod 'react-native-webview', :path => '../node_modules/react-native-webview'
      pod 'JPushRN', :path => '../node_modules/jpush-react-native'

  pod 'react-native-video', :path => '../node_modules/react-native-video'





  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end